concourse/semver-resource

README.md
check/main.go
in/main.go
models/models.go
out/main.go

Adds an option to specify a custom S3 compatible endpoint.
Default behaviour for AWS stays the same.
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>

add endpoint option for S3 compatible providers

---

driver/git.go

To help defeat this error condition: 
```
Cloning into '/tmp/semver-git-repo'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error bumping version: exit status 128
```

Host key verification failed.

---

driver/swift.go

1) Causes file to be deleted after a certain amount of time, shouldn't
use this option

Remove DeleteAfter copy paste error bug

---

README.md
driver/driver.go
driver/git.go
models/models.go

It can be nice to give the mail and username of the git user which put to the repository.
This PR add this support with the field : 
`git_user`: *Optional.*  The git identity to use when pushing to the repository support RFC 5322 address of the form "Gogh Fir <gf@example.com>" or "foo@example.com".

Adding git identity support

---

README.md
driver/driver.go
models/models.go

Minio doesn't provide a HTTPS endpoint. This is also not required when running everything on-site. Therefor disabling SSL (already provided by the AWS sdk) is an easy solution.

Add disableSSL for s3 compatible providers without SSL endpoints

---

driver/s3.go

If there are any spaces in the s3 file body (for example, if there's a trailing newline), it fails to parse the semver. This resolves that.

Remove leading/trailing spaces from s3 body

---

README.md
driver/driver.go
driver/v2signer.go
models/models.go

adding the same support for s3 driver that s3-resource has for enabling this resource to be used where v2 signing is still required.  Tested on older version of openstack ceph s3.

adding support for v2 signing for s3 driver

---

test/all.sh
test/check.sh
test/helpers.sh
test/put.sh

This is because commands like `source` and `set -o pipefail` are not supported by Bourne shell. This causes failure when running tests on systems that do not use Bourne Again Shell for `/bin/sh`.

Change shebang to use Bourne Again Shell as opposed to Bourne shell

---

README.md

The swift driver expects region, not region_name.

Update parameter name in swift docs to match code

---

driver/git.go

In reference to: https://github.com/concourse/semver-resource/issues/76
Again, we couldn't really find any unit tests for the `GitDriver` itself to modify, but we can add those as well for this change if needed.

Updated Git Driver Check to account for OpenSSH formatted keys

---

README.md

As a pipeline plumber, I'd like to know how my pipelines can use the `x.y.z-build.*` semver scheme. 
The current documentation is fuzzy (see [#68]) and makes it sound like `alpha`, `beta`, or `rc` are the only `pre` options. However, it turns out you can use _any_ convention you'd like. Example:
```yml
jobs:
- name: build
plan:
- get: version
params:
pre: build # <---- x.y.z-build.*
...
- get: version
params:
pre: my-amazing-string-prefix-convention # <--- x.y.z-my-amazing-string-prefix-convention.1
```
Although _any_ string prefix can be used, maybe it shouldn't be advertised. Maybe only semi-conventional naming setups should be advertised, such as `alpha`, `beta`, `rc`, and `build`
See [#68].

Add clarification to pre param

---

README.md
driver/driver.go
driver/driver_test.go
driver/git.go

I based myself on #50. 
If the option is set, it will run `git config http.sslVerify "false"` in the setUpRepo() method in git.go.
This solves #96.

Added skip SSL verification for git driver

---

driver/git.go

https://github.com/concourse/semver-resource/issues/89

fix issues 89

---

driver/driver.go
models/models.go

In order to use generated credentials, the aws session token needs to be set.
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
in my case, The https://github.com/telia-oss/concourse-sts-lambda generate & rotate the temporary credentials. so in order for any temporary credentials to be used, we need to set token session.
Thanks

Support for temporary security credentials, AWS S3 driver

---

driver/swift.go
driver/swift_test.go

Fixes concourse/semver-resource#21
This is the smallest change I could make to fix this issue. I'm unable
to run the "unit" tests because I do not have access (or have
personally worked with) an OpenStack environment.
The swift driver is actually the only driver with a constructor
(`NewABC()`)  function. The other drivers are constructed in
`FromSource()` where there is a copy of the `if..else` this commit adds.

[swift] make initial version optional

---

driver/gcs.go

Sometimes writing the version file to GCS can silently fail and the file is empty after a `put`. The error only surfaces on subsequent `get` or `check` (see https://github.com/concourse/semver-resource/issues/125).
This change no longer ignores errors returned when closing the GCS writer, as the [library docs](https://pkg.go.dev/cloud.google.com/go/storage#Writer.Write) state:
> Since writes happen asynchronously, Write may return a nil error even though the write failed (or will fail). Always use the error returned from Writer.Close to determine if the upload was successful.

handle error from closing GCS writer

---

README.md
out/main.go

Follow up to #131 to fix a bug where the resource would error if you tried to do a build label bump with an empty `bump` and `pre`.

Allow `puts` that only bump the build label

---

README.md
dockerfiles/alpine/Dockerfile
dockerfiles/ubuntu/Dockerfile
driver/git.go
models/models.go
out/main.go

Close #124 
---
* Introduced "check-less usage", which avoid to run checks on "semver" resources, which reduces burdens brought to the dependent systems, such as git. Refer to the README for details.
* Fixed a bug (#124) where git push errors were silently discarded.

Add get_latest param.

---

README.md

when trying the check less option i stumbled on to the issue that i could't use the passed flag for a put step.
so i would think its nice to put this in the con's list

update doc for the check-less usage

---

driver/git.go

Was verifying if #89 was still an issue, which it isn't anymore.
Closes #89

go modernize: use range instead of c-style for loop

---

README.md
driver/driver.go

also removed the v2 signing stuff. Doubt anyone was using it anyways. All current s3-compatible providers use v4 signing now.
If someone needs v2 signing they can stick with older versions of the resource.

update readme and verify aws creds earlier
